FROM ubuntu:latest

RUN apt update && apt install -y bind9 bind9utils bind9-dnsutils && rm -rf /var/lib/apt/lists/*

COPY named.conf /etc/bind/named.conf
COPY zones/ /etc/bind/zones/

EXPOSE 53/udp 53/tcp

USER bind

CMD ["named", "-g", "-u", "bind"]
