replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: ryannemeth/bind9
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 53
  targetPort: 53

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

serviceAccount:
  create: true

config:
  namedConf: |
    options {
      directory "/var/cache/bind";
      listen-on { any; };
      allow-query { any; };
      recursion no;
    };

  zoneFiles:
    examplecomdb: |
      $TTL    86400
      @       IN      SOA     ns1.example.com. admin.example.com. (
                            2024031101
                            3600
                            1800
                            604800
                            86400 )
      @       IN      NS      ns1.example.com.
      ns1     IN      A       10.0.0.1
      www     IN      A       10.0.0.2

ingress:
  enabled: true
  annotations: {}
  host: example.com
  ingressClassName: ""
  pathType: Prefix
  path: /
  
