replicaCount: 1

image:
  repository: lissy93/dashy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

dashy-config:
   pageInfo:
    title: Dashy
    description: Welcome to your new dashboard!
    navLinks:
      - title: GitHub
        path: https://github.com/Lissy93/dashy
      - title: Documentation
        path: https://dashy.to/docs
    appConfig:
      theme: material-dark
      layout: auto
      iconSize: medium
      language: en
    sections:
      - name: Getting Started
        icon: fas fa-rocket
        items:
          - title: Dashy Live
            description: Development a project management links for Dashy
            icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
            url: https://live.dashy.to/
            target: newtab
            id: 0_1481_dashylive
          - title: GitHub
            description: Source Code, Issues and Pull Requests
            icon: favicon
            url: https://github.com/rnemeth90
            id: 1_1481_github
          - title: Docs
            description: Configuring & Usage Documentation
            provider: Dashy.to
            icon: far fa-book
            url: https://dashy.to/docs
            id: 2_1481_docs
          - title: Showcase
            description: See how others are using Dashy
            url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
            icon: far fa-grin-hearts
            id: 3_1481_showcase
          - title: Config Guide
            description: See full list of configuration options
            url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
            icon: fas fa-wrench
            id: 4_1481_configguide
          - title: Support
            description: Get help with Dashy, raise a bug, or get in contact
            url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
            icon: far fa-hands-helping
            id: 5_1481_support